In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
DB_HOST = 'localhost'  
DB_PORT = '5433'           
DB_NAME = 'postgres'
DB_USER = 'postgres'
DB_PASSWORD = '11111'

In [4]:
csv_data = pd.read_csv('v_data.csv')
display(csv_data.columns.to_list())

['contour_id',
 'fuel_coefficient',
 'energy_export',
 'energy_import',
 'clock',
 'name',
 'lat',
 'lon']

In [5]:
csv_data['location_id'] = csv_data.groupby('name').ngroup() + 1

#### Column 1 - contour
- contour_id
- fuel_coefficient
- location_id

In [6]:
contour = csv_data.drop_duplicates(['contour_id', 'fuel_coefficient', 'location_id'])
contour = contour[['contour_id', 'fuel_coefficient', 'location_id']]
contour = contour.sort_values('contour_id')
display(contour)

         contour_id  fuel_coefficient  location_id
0          13836498                 1           12
671        14098248                10           11
1342       14101511                 1            3
2011       14101513                 1            5
2680       14101530                 1           12
...             ...               ...          ...
1385768    15005900                 1           13
1386432    15005913                 1            3
1387100    15005924                 1            4
1387768    15005930                 1            8
1388440    15005953                 1           13

[2083 rows x 3 columns]

#### Column 2 - locations
- location_id
- name
- lat
- lon

In [7]:
locations = csv_data.drop_duplicates(['location_id', 'name', 'lat', 'lon'])
locations = locations[['location_id', 'name', 'lat', 'lon']]
locations = locations.sort_values('name')
display(locations)

       location_id            name      lat      lon
20067            1           Balti  47.7618  27.9190
26731            2           Cahul  45.9084  28.1960
1342             3        Chisinau  47.0166  28.8499
8036             4          Comrat  46.3005  28.6601
2011             5         Cricova  47.1352  28.7611
5356             6          Edinet  48.1718  27.3079
4018             7        Floresti  47.8917  28.2992
14699            8        Hincesti  46.8317  28.5878
28744            9           Orhei  47.3792  28.8239
38763           10          Rezina  47.7481  29.0444
671             11          Soroca  48.1565  28.2995
0               12     Stefan Voda  46.5156  29.6633
4687            13        Tiraspol  46.8406  29.6083
3349            14         Ungheni  47.2106  27.8006
7365            15  Vadul lui Voda  47.1287  29.0838

#### Column 3 - contour_data
- contour_id
- energy_export
- energy_import
- clock

In [11]:
contour_data = csv_data[['contour_id', 'energy_export', 'energy_import', 'clock']]
contour_data = contour_data.sort_values(['contour_id', 'clock'])
contour_data['clock'] = pd.to_datetime(contour_data['clock'])
display(contour_data)

         contour_id  energy_export  energy_import               clock
0          13836498            469        6517117 2025-06-01 12:15:00
1          13836498            469        6517160 2025-06-01 12:30:00
2          13836498            469        6517205 2025-06-01 12:45:00
3          13836498            469        6517249 2025-06-01 13:00:00
4          13836498            469        6517296 2025-06-01 13:15:00
...             ...            ...            ...                 ...
1389103    15005953              0              0 2025-06-08 10:45:00
1389104    15005953            334           1619 2025-06-08 11:00:00
1389105    15005953              0              0 2025-06-08 11:15:00
1389106    15005953              0              0 2025-06-08 11:30:00
1389107    15005953              0              0 2025-06-08 11:45:00

[1389108 rows x 4 columns]

In [9]:
# Create the SQLAlchemy engine string
# Format: 'postgresql+psycopg2://user:password@host:port/dbname'
engine_string = f'postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'

# Create the SQLAlchemy engine
engine = create_engine(engine_string)

In [12]:
def write_to_db(df, table_name):
    df.to_sql(
        name=table_name,
        con=engine,
        if_exists='append',
        schema='public',
        index=False,
        chunksize=1000
    )

# write_to_db(locations, 'locations')
write_to_db(contour, 'contour')
write_to_db(contour_data, 'contour_data')